seed: 42
data_path: model/train/data/dataset
synth_data:
  labeling:
    peak_area: 3
    max_area: 3
  peak_types:
    large:
      scale:
        val: 6
        var: 18
      const:
        val: 0.8
        var: 0.2
      gl_const:
        val: 0.6
        var: 0.4
      background_const:
        val: 0.02
        var: 0.03
      overlapping:
        val: 1
        var: 0
    medium:
      scale:
        val: 10
        var: 14
      const:
        val: 0.4
        var: 0.3
      gl_const:
        val: 0.7
        var: 0.2
      background_const:
        val: 0.01
        var: 0.01
      overlapping:
        val: 1
        var: 0
    impurity:
      scale:
        val: 20
        var: 10
      const:
        val: 0.075
        var: 0.15
      gl_const:
        val: 0.8
        var: 0.2
      background_const:
        val: 0
        var: 0
      overlapping:
        val: 1
        var: 0
    satellite:
      scale:
        val: 4
        var: 5
      const:
        val: 0.055
        var: 0.045
      gl_const:
        val: 1
        var: 0
      background_const:
        val: 0
        var: 0
      overlapping:
        val: 0
        var: 0
  spectrum_params:
    len: 256
    noise:
      val: 0.03
      size: 120
      var: 100
    shakeup: 0.002
    n_of_peaks:
      large: 1-2
      medium: 0-1
      impurity: 0-1
      satellite: 1-4
  dataset_size: 10000
train:
  num_epoch: 400
  batch_size: 500
  learning_rate: 0.0005
  train_test_split: 0.8
