seed_everything: 42

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 400
  enable_progress_bar: true
  default_root_dir: logs
  logger: false
  enable_checkpointing: false
  callbacks:
    - class_path: model.train.lightning_callbacks.ClearMLCallback
      init_args:
        project: XPS-Peak-Detection
        task_name: Lightning-Training
        monitor: val_loss
        file_name: best_model.pt
        artifact_name: best_model

model:
  learning_rate: 0.0005
  dicefocal_weight: 5.0

data:
  params_path: model/params.yaml
  seed: 42
  train_data: ../model/train/data/train
  val_data: ../model/train/data/val
  train:
    batch_size: 500
    train_test_split: 0.8
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  generate_synth: false
  generate_synth_train: true
  generate_synth_val: true
  synth_train_size: 10000
  synth_val_size: 2500

# python train_lightning.py fit --config configs\lightning.yaml
